### PR TITLE
DigitalShadows-SOAR: Bug Fixes - Fixes for one action

### PR DESCRIPTION
**Pull request by devang-metron**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [x] Testing of all the changes has been performed (for bug fixes / features)
- [x] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [x] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [x] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [x] Verify all checks are passing.
- [x] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [x] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers), 
  please document them in the `readme.html`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `readme.html` all methods (eg, OAuth) used to authenticate 
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `readme.html`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through 
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

  

## Release Notes (REQUIRED)
- Bug fixes for actions 'search incidents'

### CODE REVIEW

**Comment by spopat-crest** [comment]
Hello @devang-metron, Please let us know once you are done with the changes and the PR is ready for review.
Thank you.

**Comment by spopat-crest** [comment]
Hello @devang-metron, We noticed that the PR is marked as Draft, please let us know once it is ready for review.
Thank you

**Comment by yashwanth-metron** [comment]
@spopat-crest min_phantom_version : `5.2.0` but it is also compatible with >`5.3.0`, testing has been done on `v5.4.0`.

**Comment by spopat-crest** [comment]
@yashwanth-metron Thanks for the update. Currently, the expected min_phantom_version is 5.3.5, so please update it to that in the JSON file.
And if all the changes and testing is done, could you move the PR to the open stage, so we can proceed with further activities?

**Comment by yashwanth-metron** [comment]
Hey @spopat-crest, We have been trying to install version 5.3.5 but we did not find any OVA file we could only find the TARBALL file.
could you please send us an installation guide for that?

**Comment by spopat-crest** [comment]
@yashwanth-metron Here are the steps to install Splunk SOAR from the tarball file https://docs.splunk.com/Documentation/SOARonprem/5.3.5/Install/InstallUnprivileged

**Comment by spopat-crest** [comment]
Hello, @yashwanth-metron @devang-metron any update on the PR?

**Comment by yashwanth-metron** [comment]
Hey @spopat-crest, We are currently still under going testing will let you know once completed and change PR status.

**Comment by aparekh-crest** [comment]
Hello @devang-metron, merging this pr into [#6](https://github.com/splunk-soar-connectors/digitalshadows/pull/6) this PR for further changes.

**Pull request merged**
