### PR TITLE
Digital shadows 2.1.1

### PR DESCRIPTION
**Pull request by yash-metron**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [x] Testing of all the changes has been performed (for bug fixes / features)
- [x] The manual_readme_content.md has been reviewed and added / updated if needed (for bug fixes / features)
- [x] Use the following format for the PR description: `DigitalShadows: BugFix - Updated the "label", label which are present in the config`
- [x] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [x] Verify all checks are passing.
- [x] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [x] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe):

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers),
  please document them in the `manual_readme_content.md`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `manual_readme_content.md` all methods (eg, OAuth) used to authenticate
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `manual_readme_content.md`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

## Release Notes (REQUIRED)
- We have added the release note :- Updated the "label", label which are present in the config

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by yash-metron** [comment]
We tried updating the minimum product version from 5.3.5 to 6.1.1 but still we are getting the version error which stats that :-
```
{
    "FAILED": {
        "CRITICAL": [
            {
                "min_platform_version": {
                    "description": "Checks that if pip packages are installed, phantom version > CURRENT_MIN_PHANTOM_VERSION",
                    "expected": "Min Phantom version in app json is too low. Found: \"5.3.5\" but expected >= \"5.5.0\"",
                    "message": "TEST WAS EXPECTED TO FAIL, BUT PASSED",
                    "success": false,
                    "verbose": [
                        "TEST WAS EXPECTED TO FAIL, BUT PASSED"
                    ]
                }
            }
        ],
        "NONCRITICAL": []
    }
```

**Comment by yash-metron** [comment]
@splunk-soar-connectors-admin Can you please help me with the above comment?
Thanks!

**Comment by mishalp-crest** [comment]
@yash-metron 
Pipeline failures will be managed by us
Kindly provide write access so that we can add standard dev check changes.

**Comment by devang-metron** [comment]
@mishalp-crest We have granted the write access.

**Review by alexa-phantom — APPROVED** [review]

**Review by alexa-phantom — CHANGES_REQUESTED** [review]
After checking the FOSSA, please make updates to get FOSSA passing

**Comment by devang-metron** [comment]
@mishalp-crest Can you please let me know if we need to make any change about the FOSSA passing? As I am not aware of such process.

**Comment by mishalp-crest** [comment]
> @mishalp-crest Can you please let me know if we need to make any change about the FOSSA passing? As I am not aware of such process.

@devang-metron I am working on it only
will soon release the app

**Comment by mishalp-crest** [comment]
@yash-metron @devang-metron 
We have done some standard dev changes 
Let us know if you have doubt or concern

**Comment by devang-metron** [comment]
Hey @mishalp-crest,
Just one doubt, app version and min phantom version are mismatching in Readme and manifest files. Is it fine?
Thanks!

**Comment by mishalp-crest** [comment]
> Hey @mishalp-crest, Just one doubt, app version and min phantom version are mismatching in Readme and manifest files. Is it fine? Thanks!

For readme it will be automatically managed
What do you mean by manifest file?

**Comment by devang-metron** [comment]
@mishalp-crest by manifest, I mean digitalshadows.json file.
Thanks for the info.

**Comment by mishalp-crest** [comment]
@yash-metron @devang-metron 
Do you want to keep a specific version of the certifi?

**Comment by devang-metron** [comment]
@mishalp-crest It should be fine. We will give one sanity though.

**Review by alexa-phantom — APPROVED** [review]

**Review by dhwanis-crest — APPROVED** [review]

**Pull request merged**
